### ISSUE TITLE
YOLOV5 onnx2caffe?

### ISSUE THREAD

**Issue by china56321** [205418367/TransOnnxToCaffe#3]
请问支持YOLOV5吗？我转YOLOV5.ONNX 为CAFFE时报错：
Traceback (most recent call last):
  File "convertCaffe.py", line 107, in <module>
    convertToCaffe(graph, prototxt_path, caffemodel_path)
  File "convertCaffe.py", line 52, in convertToCaffe
    layer = converter_fn(node, graph, err)
  File "/home/make/onnx2caffe/onnx2caffe/_operators.py", line 405, in _convert_conv_slice
    return err.unsupported_op_configuration(node, "Only single axis Slice is supported now")
  File "/homel/make/onnx2caffe/onnx2caffe/_error_utils.py", line 44, in unsupported_op_configuration
    raise TypeError(
TypeError: Error while converting op of type: Slice. Error message: Only single axis Slice is supported now

我转你提供的模型best-sim.onnx也报错：
I0820 12:13:02.236326  8983 net.cpp:408] Resize_125 -> 294
F0820 12:13:02.236367  8983 base_conv_layer.cpp:46] Check failed: kernel_shape_data[i] > 0 (0 vs. 0) Filter dimensions must be nonzero.
*** Check failure stack trace: ***
Aborted (core dumped)

**Comment by 205418367** [comment]
支持yolo5,我亲自转过

**Comment by china56321** [comment]
> 支持yolo5,我亲自转过

有试过检测视频或图片吗？正常吗？

**Comment by 205418367** [comment]
正常

**Comment by 205418367** [comment]
用我的代码可以直接转，不过要安装ssd-caffe

**Comment by china56321** [comment]
> 用我的代码可以直接转，不过要安装ssd-caffe

你好，我刚转你提供的best.onnx到caffemodel模型，报以下错误：
Traceback (most recent call last):
  File "convertCaffe.py", line 107, in <module>
    convertToCaffe(graph, prototxt_path, caffemodel_path)
  File "convertCaffe.py", line 48, in convertToCaffe
    err.unsupported_op(node)
  File "/home/make/onnx2caffe/onnx2caffe/_error_utils.py", line 35, in unsupported_op
    raise TypeError(
TypeError: ONNX node of type Shape is not supported.
请问这怎么解决？

**Comment by 205418367** [comment]
了解一下onnx-simplifier

**Comment by china56321** [comment]
> onnx-simplifier
刚转了onnx-simplifier.又报以下错误：
Traceback (most recent call last):
  File "convertCaffe.py", line 107, in <module>
    convertToCaffe(graph, prototxt_path, caffemodel_path)
  File "convertCaffe.py", line 48, in convertToCaffe
    err.unsupported_op(node)
  File "/home/make/onnx2caffe/onnx2caffe/_error_utils.py", line 35, in unsupported_op
    raise TypeError(
TypeError: ONNX node of type Resize is not supported.

**Comment by china56321** [comment]
> > onnx-simplifier
> > 刚转成功onnx-simplifier.
又用你的代码转CAFFEMODEL报以下错误：
> > Traceback (most recent call last):
> > File "convertCaffe.py", line 107, in 
> > convertToCaffe(graph, prototxt_path, caffemodel_path)
> > File "convertCaffe.py", line 48, in convertToCaffe
> > err.unsupported_op(node)
> > File "/home/make/onnx2caffe/onnx2caffe/_error_utils.py", line 35, in unsupported_op
> > raise TypeError(
> > TypeError: ONNX node of type Resize is not supported.

**Comment by 205418367** [comment]
这个需要修改我的代码，暂时onnx2caffe不支持 resize

**Comment by china56321** [comment]
> 这个需要修改我的代码，暂时onnx2caffe不支持 resize

你之前不是已经转成功了吗？请问在哪里修改？怎么修改？

**Comment by AIxuxu** [comment]
> > 这个需要修改我的代码，暂时onnx2caffe不支持 resize
> 
> 你之前不是已经转成功了吗？请问在哪里修改？怎么修改？

请问一下，你现在转换成功了吗

**Comment by AIxuxu** [comment]
> 这个需要修改我的代码，暂时onnx2caffe不支持 resize

请问怎么修改，我现在也在做转换YOLOv5的转换

**Comment by Wulingtian** [comment]
![IMG_20201230_164509](https://user-images.githubusercontent.com/20986422/103340248-8de88680-4abe-11eb-9c3e-6a1da0eb016b.jpg)
成功转换yolov5！

**Comment by AIxuxu** [comment]
> ![IMG_20201230_164509](https://user-images.githubusercontent.com/20986422/103340248-8de88680-4abe-11eb-9c3e-6a1da0eb016b.jpg)
> 成功转换yolov5！

请问一下，v5的focus层以及upsample层您是怎样处理的

**Comment by Wulingtian** [comment]
> > ![IMG_20201230_164509](https://user-images.githubusercontent.com/20986422/103340248-8de88680-4abe-11eb-9c3e-6a1da0eb016b.jpg)
> > 成功转换yolov5！
> 
> 请问一下，v5的focus层以及upsample层您是怎样处理的

focus 层我用卷积层代替了，upsample层我没有报错

**Comment by Wulingtian** [comment]
> > ![IMG_20201230_164509](https://user-images.githubusercontent.com/20986422/103340248-8de88680-4abe-11eb-9c3e-6a1da0eb016b.jpg)
> > 成功转换yolov5！
> 
> 请问一下，v5的focus层以及upsample层您是怎样处理的

你是用yolov5 3.0版本转的？

**Comment by AIxuxu** [comment]
> > > ![IMG_20201230_164509](https://user-images.githubusercontent.com/20986422/103340248-8de88680-4abe-11eb-9c3e-6a1da0eb016b.jpg)
> > > 成功转换yolov5！
> > 
> > 
> > 请问一下，v5的focus层以及upsample层您是怎样处理的
> 
> focus 层我用卷积层代替了，upsample层我没有报错

你是用作者这个版本的onnx2caffe吗

**Comment by AIxuxu** [comment]
> > > ![IMG_20201230_164509](https://user-images.githubusercontent.com/20986422/103340248-8de88680-4abe-11eb-9c3e-6a1da0eb016b.jpg)
> > > 成功转换yolov5！
> > 
> > 
> > 请问一下，v5的focus层以及upsample层您是怎样处理的
> 
> 你是用yolov5 3.0版本转的？

是yolov5 2.0版本的，遇到问题了

**Comment by Wulingtian** [comment]
> > > > ![IMG_20201230_164509](https://user-images.githubusercontent.com/20986422/103340248-8de88680-4abe-11eb-9c3e-6a1da0eb016b.jpg)
> > > > 成功转换yolov5！
> > > 
> > > 
> > > 请问一下，v5的focus层以及upsample层您是怎样处理的
> > 
> > 
> > 你是用yolov5 3.0版本转的？
> 
> 是yolov5 2.0版本的，遇到问题了

我之前用3.1版本不行，也换成2.0的了，我是用这个作者的

**Comment by AIxuxu** [comment]
> > > > > ![IMG_20201230_164509](https://user-images.githubusercontent.com/20986422/103340248-8de88680-4abe-11eb-9c3e-6a1da0eb016b.jpg)
> > > > > 成功转换yolov5！
> > > > 
> > > > 
> > > > 请问一下，v5的focus层以及upsample层您是怎样处理的
> > > 
> > > 
> > > 你是用yolov5 3.0版本转的？
> > 
> > 
> > 是yolov5 2.0版本的，遇到问题了
> 
> 我之前用3.1版本不行，也换成2.0的了，我是用这个作者的

好的，你也是把yolov5移植到海思上吗，看看caffe模型是否正确，能加你联系方式吗

**Comment by Wulingtian** [comment]
> > > > > > ![IMG_20201230_164509](https://user-images.githubusercontent.com/20986422/103340248-8de88680-4abe-11eb-9c3e-6a1da0eb016b.jpg)
> > > > > > 成功转换yolov5！
> > > > > 
> > > > > 
> > > > > 请问一下，v5的focus层以及upsample层您是怎样处理的
> > > > 
> > > > 
> > > > 你是用yolov5 3.0版本转的？
> > > 
> > > 
> > > 是yolov5 2.0版本的，遇到问题了
> > 
> > 
> > 我之前用3.1版本不行，也换成2.0的了，我是用这个作者的
> 
> 好的，你也是把yolov5移植到海思上吗，看看caffe模型是否正确，能加你联系方式吗

WeChat：willer199311
