### ISSUE TITLE
TypeError: ONNX node of type Clip is not supported.

### ISSUE THREAD

**Issue by zgh2022** [205418367/TransOnnxToCaffe#4]
How to solve Clip

**Comment by 205418367** [comment]
clip就是relu6,caffe不支持relu6,但是可以修改caffe源码。

**Comment by zgh2022** [comment]
原来如此！

**Comment by zgh2022** [comment]
我修改好了，也simple了模型，现在出了这些问题：
ARNING: Logging before InitGoogleLogging() is written to STDERR
E0909 11:32:10.622145 14916 common.cpp:123] Cannot create Cublas handle. Cublas won't be available.
E0909 11:32:10.626135 14916 common.cpp:130] Cannot create Curand generator. Curand won't be available.
Traceback (most recent call last):
  File ".../onnx2caffe-master/convertCaffe.py", line 109, in <module>
    convertToCaffe(graph, prototxt_path, caffemodel_path)
  File ".../onnx2caffe-master/convertCaffe.py", line 64, in convertToCaffe
    layers[id] = layer._to_proto()
  File "...\onnx2caffe-master\MyCaffe.py", line 100, in _to_proto
    assign_proto(layer, k, v)
  File ".../onnx2caffe-master\MyCaffe.py", line 29, in assign_proto
    is_repeated_field = hasattr(getattr(proto, name), 'extend')
AttributeError: permute_param
我不知道该怎么解决了

**Comment by Wulingtian** [comment]
> 我修改好了，也simple了模型，现在出了这些问题：
> ARNING: Logging before InitGoogleLogging() is written to STDERR
> E0909 11:32:10.622145 14916 common.cpp:123] Cannot create Cublas handle. Cublas won't be available.
> E0909 11:32:10.626135 14916 common.cpp:130] Cannot create Curand generator. Curand won't be available.
> Traceback (most recent call last):
> File ".../onnx2caffe-master/convertCaffe.py", line 109, in
> convertToCaffe(graph, prototxt_path, caffemodel_path)
> File ".../onnx2caffe-master/convertCaffe.py", line 64, in convertToCaffe
> layers[id] = layer._to_proto()
> File "...\onnx2caffe-master\MyCaffe.py", line 100, in _to_proto
> assign_proto(layer, k, v)
> File ".../onnx2caffe-master\MyCaffe.py", line 29, in assign_proto
> is_repeated_field = hasattr(getattr(proto, name), 'extend')
> AttributeError: permute_param
> 我不知道该怎么解决了
你好请问这个问题解决了吗？我也出现这个问题
