### ISSUE TITLE
转换yolov5，报Inferred shape and existing shape differ in dimension 2: (640) vs (320)

### ISSUE THREAD

**Issue by Wulingtian** [205418367/TransOnnxToCaffe#5]
Traceback (most recent call last):
  File "convertCaffe.py", line 106, in <module>
    graph = getGraph(onnx_path)
  File "convertCaffe.py", line 93, in getGraph
    model = shape_inference.infer_shapes(model)
  File "/usr/local/lib/python2.7/dist-packages/onnx/shape_inference.py", line 35, in infer_shapes
    inferred_model_str = C.infer_shapes(model_str, check_type)
RuntimeError: Inferred shape and existing shape differ in dimension 2: (640) vs (320)

**Comment by Albert666** [comment]
我也遇到了
